theme: jekyll-theme-cayman
title: "Forschungsdesign &quot;korpusbasierte Textanalyse&quot;&colon; Ein Figurenverzeichnis anhand automatischer Personenenerkennung erstellen"
description: Tutorial für CLARIAH-DE
baseurl: /clariah_forschungsdesign_textanalyse