theme: jekyll-theme-cayman
title: "Forschungsdesign \"korpusbasierte Textanalyse\": Ein Figurenverzeichnis anhand automatischer Personenenerkennung erstellen"
description: Tutorial für CLARIAH-DE
baseurl: /clariah_forschungsdesign_textanalyse