theme: jekyll-theme-cayman
title: "Forschungsdesign \"korpusbasierte Textanalyse\": Ein Figurenverzeichnis anhand automatischer Personenenerkennung erstellen"
baseurl: /clariah_forschungsdesign_textanalyse